apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confessionsdb-data-disk
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql3-deployment
  labels:
    app: mysql3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql3
  template:
    metadata:
      labels:
        app: mysql3
    spec:
      nodeName: minikube # schedule pod to specific node
      containers:
        - name: pod-confessions
          image: riadaple/confessions:latest 
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
          - containerPort: 80

        - name: mysql3
          image: mysql:5.7
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: confessionsdb-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: confessionsdb-secret
                  key: ROOT_PASSWORD
      volumes:
        - name: confessionsdb-data
          persistentVolumeClaim:
            claimName: confessionsdb-data-disk