apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dictionarydb-data-disk
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql2-deployment
  labels:
    app: mysql2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql2
  template:
    metadata:
      labels:
        app: mysql2
    spec:
      nodeName: minikube # schedule pod to specific node
      containers:
        - name: pod-dictionary
          image: riadaple/dictionary:latest 
          imagePullPolicy: Always
          ports:
          - containerPort: 83

        - name: mysql2
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: dictionarydb-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dictionarydb-secret
                  key: ROOT_PASSWORD
      volumes:
        - name: dictionarydb-data
          persistentVolumeClaim:
            claimName: dictionarydb-data-disk