apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql4-deployment
  labels:
    app: mysql4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql4
  template:
    metadata:
      labels:
        app: mysql4
    spec:
      nodeName: minikube # schedule pod to specific node
      containers:
        - name: pod-movie
          image: riadaple/movie:latest 
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
          - containerPort: 80

        - name: mysql
          image: mysql:5.7
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: moviedb-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: moviedb-secret
                  key: ROOT_PASSWORD
      volumes:
        - name: moviedb-data
          persistentVolumeClaim:
            claimName: moviedb-data-disk