---
apiVersion: v1
kind: Service
metadata:
  name: booksapp-service
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: mysql