---
apiVersion: v1
kind: Service
metadata:
  name: confessionsapp-service
  labels:
    app: mysql3
spec:
  type: NodePort
  ports:
  - port: 8008
    targetPort: 80
    nodePort: 30003
    protocol: TCP
  selector:
    app: mysql3