---
apiVersion: v1
kind: Service
metadata:
  name: dictionaryapp-service
  labels:
    app: mysql2
spec:
  type: NodePort
  ports:
  - port: 8002
    targetPort: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: mysql2