---
apiVersion: v1
kind: Service
metadata:
  name: movieapp-service
  labels:
    app: mysql4
spec:
  type: NodePort
  ports:
  - port: 8004
    targetPort: 80
    nodePort: 30004
    protocol: TCP
  selector:
    app: mysql4